### ISSUE TITLE
When there's a new chat with unread blue mark, it breaks the automation.

### ISSUE THREAD

**Issue by Schieck** [qcrao/bulk-delete-chatGPT#25]
If you have any conversation with the blue mark (Not read chat) it breaks the process and do not delete.

**Comment by Schieck** [comment]
Thanks @qcrao for creating the automation, it's really helpful.

**Comment by qcrao** [comment]
> If you have any conversation with the blue mark (Not read chat) it breaks the process and do not delete.

Thanks for reminding. I'll fix it soon. when new version is approved, I'll notify here.

**Comment by Schieck** [comment]
Nice! I really don't know why OpenAi do not have this feature, their experience deleting data is really poor, chats keeps reappearing and the experience to delete is crap, specially if you use it daily.

**Comment by MNOiSY** [comment]
Same issue. I look forward to the fix

**Comment by qcrao** [comment]
Thank you all for your patience and feedback! I’ve released an updated version. However, due to limitations in the extension’s implementation, it can’t delete unread conversations. I apologize for any inconvenience this may cause. To help users who may not be aware of this restriction, the extension will now show a confirmation dialog that requires manual interaction to continue with the deletion process. Thanks again for your understanding and support!

@Schieck @MNOiSY
